Program now exits if find command fails.

diff --git a/dirgraph b/dirgraph
--- a/dirgraph
+++ b/dirgraph
@@ -76,24 +76,35 @@ if [ $# -eq 1 ]; then
 fi
 
 # loop through folders
-for line in $(find "$path" -type d 2>/dev/null); do
+command=$(find "$path" -type d 2>/dev/null)
+if [ $? -ne 0 ]; then
+	echo "An error occured" 1>&2
+	exit 1
+fi
+for line in $command; do
 
 	# if `-i` is provided
 	if [ $i -eq 1 ]; then
 		# if some file is not matched by the regex, count the folder
-		if [ 0 -lt "$(find "$line" -type f 2>>/dev/null | grep -c -q -v -E "$ivalue")" ]; then
+		if [ 0 -lt "$(find "$line" -type f 2>/dev/null | grep -c -q -v -E "$ivalue")" ]; then
 			dirs=$((dirs + 1))
 		fi
 	else
 		# if some file is not matched by the regex, count the folder
-		if [ 0 -lt "$(find "$line" -type f 2>>/dev/null | wc -l)" ]; then
+		if [ 0 -lt "$(find "$line" -type f 2>/dev/null | wc -l)" ]; then
 			dirs=$((dirs + 1))
 		fi
 	fi
 
 done
 
-for line in $(find "$path" -type f 2>>/dev/null); do
+# loop through files
+command=$(find "$path" -type f 2>/dev/null)
+if [ $? -ne 0 ]; then
+	echo "An error occured" 1>&2
+	exit 1
+fi
+for line in $command; do
 
 	if [ $i -eq 1 ]; then
 		if basename "$line" | grep -q -E "$ivalue"; then
